# Permalinks
permalink:           pretty

# Setup
title:               Szkoła IF
tagline:             Szkoła IF
description:         ""
email:               filipczaplicki@gmail.com
baseurl:             "/"
url:                 "https://inwitofitka.club"
paginate:            1

# Custom vars

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - deploy.sh
